# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 16:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20160526_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='omegaup_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='site',
            field=models.IntegerField(choices=[(1, 'Arequipa'), (2, 'Cusco')], default=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)', 'Ingrese un email válido')]),
        ),
    ]
